# Dies ist das Blueprint des Files Template "Default"
# In Files Blueprints können zuisatfelder für Dateien definiert und Kirby Regeln vorgegeben werden, wie mit den Dateien umgegangen werden soll.

title: Standard Datei
