title: Site
unlisted: false
templates: font

tabs:
  tab1:
    label: Dashboard
    icon: dashboard
    columns:
      - width: 1/4
          sections:
            welcome:
              type: fields
              fields:
                info:
                  type: info
                  theme: none
                  label: Willkommen im Kirby Panel 🎉
                  text: |
                    Hi, das hier ist das Panel von Kirby. Hier kannst du deine Website verwalten und Inhalte hinzufügen.


      - width: 3/4
          sections: 
            allPages:
              headline: Hauptseiten
              type: pages
              image: 
                query: icon
                back: black 